version: "2"
services:
  app:
    build: ./app
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  front:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  apitest:
    build: ./test
    volumes:
      - ./test:/tests
    depends_on:
      - front
