version: "2"
services:
  app:
    build: ./app
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    links:
      - "db:db"
    depends_on:
      - db

  db:
    image: mariadb:10.1.20
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./database/data:/docker-entrypoint-initdb.d

  front:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  apitest:
    build: ./test
    volumes:
      - ./test:/tests
    depends_on:
      - front
