version: "3"

services:
  app:
    build: ./app
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app/src:/app/src
    links:
      - db:db
    depends_on:
      - db
      - front

  db:
    image: mariadb:10.1.20
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./database/data:/docker-entrypoint-initdb.d

  front:
    build: ./nginx
    restart: always
    ports:
      - 80:80
